/*
  Copyright (C) 2010-2014 Modeling Virtual Environments and Simulation
  (MOVES) Institute at the Naval Postgraduate School (NPS)
  http://www.MovesInstitute.org and http://www.nps.edu
 
  This file is part of Mmowgli.
  
  Mmowgli is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  any later version.

  Mmowgli is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Mmowgli in the form of a file named COPYING.  If not,
  see <http://www.gnu.org/licenses/>
*/

package edu.nps.moves.mmowgli.db.pii;
import javax.persistence.*;
import javax.persistence.Entity;

import org.hibernate.annotations.*;
import org.hibernate.annotations.Parameter;
import org.jasypt.hibernate4.type.EncryptedStringType;

/**
 * Vip.java
 * Created on May 8, 2012
 *
 * MOVES Institute
 * Naval Postgraduate School, Monterey, CA, USA
 * www.nps.edu
 *
 * @author Mike Bailey, jmbailey@nps.edu
 * @version $Id$
 */

/** Used for jasypt encryption of fields */

@TypeDef(
      name="encryptedString", 
      typeClass=EncryptedStringType.class, 
      parameters={@Parameter(name="encryptorRegisteredName",
                             value="propertiesFileHibernateStringEncryptor")}
  )
  
@Entity
public class VipPii
{
  static public enum VipType {
    
    DOMAIN,EMAIL,EMAIL_BLACKLIST;
    
    public String description()
    {
      switch(this) {
        case DOMAIN: return "Domain";
        case EMAIL: return "Individual"; 
        case EMAIL_BLACKLIST: return "Individual blacklist";
      }
      throw new AssertionError("Unknown op: " + this);
    }
  };
  
  long   id;    /** Primary key, autogenerated */
  VipType   type;
  String entry;
  
  public VipPii()
  {
    
  }
  public VipPii(String entry, VipType typ)
  {
    setEntry(entry);
    setType(typ);
  }

  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  @Column(nullable = false)
  public long getId()
  {
    return id;
  }

  public void setId(long id)
  {
    this.id = id;
  }

  @Type(type="encryptedString")
  public String getEntry()
  {
    return entry;
  }

  public void setEntry(String entry)
  {
    this.entry = entry;
  }

  @Basic
  public VipType getType()
  {
    return type;
  }

  public void setType(VipType type)
  {
    this.type = type;
  }
  
  public String toString()
  {
    return getEntry();
  }
}
